# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

jobs:

  build:
    
    runs-on: ubuntu-latest
    steps:
  
      - uses: actions/checkout@v2
        
     # - name: Build Project
     #   run: mvn clean package 
        
     # - name: Varify
     #   run: ls
     #   working-directory: ./target
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3
        
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.CR_PAT }}
